GET http://localhost:5000/feedback

###
GET http://localhost:5000/feedback/9

###
POST http://localhost:5000/feedback
Content-Type: application/json

{
    "nama": "kevin",
    "komentar": "sangat baik"
}

# {
#     "nama": "Jason",
#     "komentar": "website baik. tempat wisata banyak mengalami perkembangan"
# }

# {
#     "nama": "Puji",
#     "komentar": "Website memiliki tampilan antarmuka yang mudah digunakan"
# }

# {
#     "nama": "Vaness",
#     "komentar": "banyak rekomendasi tempat wisata baru di daerah SULUT"
# }

# {
#     "nama": "Kezia",
#     "komentar": "website mudah digunakan"
# }

###
PATCH http://localhost:5000/feedback/1
Content-Type: application/json

{
    "nama": "",
    "komentar": ""
}

###
DELETE http://localhost:5000/feedback/1
